#define ANIM_DEF_SIZE (4)
#define ANIM_DEF_NUM 255

#define SPRITE_ENTRY_SIZE (4)
#define SPRITE_ENTRIES_NUM 64
#define DISPLAY_PIXELS_X (25 * 8)
#define DISPLAY_PIXELS_Y (19 * 8)

#define SPRITE_DEF_NUM 255
#define SPRITE_DEF_PIXELS_X 8
#define SPRITE_DEF_PIXELS_Y 8
#define SPRITE_DEF_PIXELS_NUM (SPRITE_DEF_PIXELS_X * SPRITE_DEF_PIXELS_Y)
#define SPRITE_DEF_SIZE (SPRITE_DEF_PIXELS_NUM)
#define SPRITE_DEF_MEM_SIZE (SPRITE_DEF_SIZE * SPRITE_DEF_NUM)

#define STACK_SIZE (2 * 1024)
#define PIXELS_SIZE (SPRITE_ENTRIES_PIXELS_Y * SPRITE_ENTRIES_PIXELS_X)

#define REG_VIDEO_ON (REG_PALETTE_BASE + PALETTE_DEF_COLOURS_NUM)

#define SPRITE_TABLE_ADDR (8 * 1024)
#define TILE_TABLE_ADDR (SPRITE_TABLE_ADDR + (SPRITE_ENTRIES_NUM * SPRITE_ENTRY_SIZE))
#define PPU_REGS_ADDR (TILE_TABLE_ADDR + (SPRITE_ENTRIES_NUM * SPRITE_ENTRY_SIZE))
#define SPRITE_DEFS_ADDR (16 * 1024)
#define PIXEL_MAP_ADDR ((unsigned long)32 * 1024)
#define CPU_SPRITE_TABLE_ADDR (48 * 1024)

#define ANIM_SPRITE_OFFSET(ANIM_METADATA) (ANIM_METADATA & 0xb111)
#define ANIM_PALETTE_OFFSET(ANIM_METADATA) ((ANIM_METADATA & 0xb11000000) >> 6)
#define ANIM_X_OFFSET(ANIM_POS_OFFSETS) (ANIM_POS_OFFSETS & 0xb1111)
#define ANIM_Y_OFFSET(ANIM_POS_OFFSETS) ((ANIM_POS_OFFSETS & 0xb11110000) >> 4)

#define PPU_CPU_INT_PORT 0
